### ISSUE TITLE
How to migrate a production DB instance?

### ISSUE THREAD

**Issue by yasserlens** [vendure-ecommerce/v2-migration-testbed#3]
Hello!

How would one approach migrating a production DB using this tool?
For example, a Google CloudSQL instance.

Hints or tips would be great.

Thanks

**Comment by michaelbromley** [comment]
The way I did it was like this:

1. Set up the migration file locally per the instructions
2. Test thoroughly
3. Schedule some downtime. The amount of time needed mainly depends on how many order records are being migrated. In our case, we had over 500k orders to migrate and it took a few minutes, maybe about 5.
4. Push the migration file to production
5. Run it on a single instance
6. Once complete, start any other instances & worker(s).

This assumes that you already have a workflow to automatically run migrations on startup like this:

```ts
import { bootstrap, runMigrations } from '@vendure/core';
import { config } from './vendure-config';

runMigrations(config)
    .then(() => bootstrap(config))
    .catch(err => {
        console.log(err);
    });
```

**Comment by yasserlens** [comment]
Thanks very much, Michael!

2 Questions:
We run on CloudSQL
**1) Re # 5. Run it on a single instance: this is referring to the Vendure service, not the DB service. correct?**
We run the Vendure servers on a Google CloudRun service, and the DB (PostgreSQL) on a managed auto-scaling Google CloudSQL.

**2) The worker: should it be down during the migration run?**

**Comment by michaelbromley** [comment]
1: yes, the Vendure service
2: Yes, it is safer to have it off during the migration because there will be a mismatch between the worker logic & the database schema until the migration is complete, which could potentially cause unexpected behaviour.

**Comment by yasserlens** [comment]
Thanks very much - will try this and report back if there's anything I can add to the above. I'll close this for now.
