### ISSUE TITLE
Typo in migration file

### ISSUE THREAD

**Issue by koljam** [vendure-ecommerce/v2-migration-testbed#5]
https://github.com/vendure-ecommerce/v2-migration-tool/blob/7f41ef6e19dc64fd82a807f706e81296bc9f99cd/src/migrations/1681467211945-v2-beta1-mysql.ts#LL3C1-L3C73

`// In your migration, you would import this from '@vendure/migration-v2'`
should be
`// In your migration, you would import this from '@vendure/migrate-v2'`

**Comment by michaelbromley** [comment]
Thanks for the report 👍
